apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-coffe-config
data:
  rabbitmq-host: "rabbitmq-service"
  rabbitmq-port: "5672"
  rabbitmq-virtualhost: "/"
  rabbitmq-exchange: "lab.coffe"
  elasticsearch-uri: "http://elasticsearch:9200"
  serilog-index-format: "lab-coffe-logs-{0:yyyy.MM.dd}"
