apiVersion: v1
kind: Secret
metadata:
  name: lab-coffe-secrets
type: Opaque
stringData:
  connectionstring: "Server=sqlserver-service;Database=LabCoffe;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=true;"
  rabbitmq-username: "guest"
  rabbitmq-password: "guest"
